project:
  type: website

website:
  title: "Diane Jang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: work.qmd
        text: Work Experiences
      - href: projects.qmd
        text: Projects
        
  page-footer:
    right: "&copy; 2024, Diane Jang"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



execute: 
  freeze: auto
